#!/usr/bin/env bash
# Syncs plugins/quicknode/skills/quicknode-skill/ from quiknode-labs/blockchain-skills@main.
# Exits non-zero if files changed (for CI drift detection).
set -euo pipefail

OWNER="quiknode-labs"
REPO="blockchain-skills"
BRANCH="main"
# Upstream path within blockchain-skills (used for the remote fetch URLs).
UPSTREAM_SKILL_PATH="skills/quicknode-skill"
# Local path within this repo (where the synced files land + drift is checked).
SKILL_PATH="plugins/quicknode/skills/quicknode-skill"
API_BASE="https://api.github.com/repos/${OWNER}/${REPO}"
RAW_BASE="https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${SCRIPT_DIR}/../${SKILL_PATH}"

# ---------- helpers ----------

need() { command -v "$1" &>/dev/null || { echo "ERROR: $1 is required but not installed." >&2; exit 1; }; }
need curl
need python3

fetch_json() { curl -fsSL "${1}" ${GITHUB_TOKEN:+--header "Authorization: Bearer ${GITHUB_TOKEN}"}; }
fetch_raw()  { curl -fsSL "${1}" ${GITHUB_TOKEN:+--header "Authorization: Bearer ${GITHUB_TOKEN}"}; }

# ---------- resolve upstream commit SHA ----------

echo "→ Resolving upstream commit SHA for ${OWNER}/${REPO}@${BRANCH}/${UPSTREAM_SKILL_PATH} ..."
COMMIT_SHA=$(fetch_json "${API_BASE}/commits?path=${UPSTREAM_SKILL_PATH}&per_page=1&sha=${BRANCH}" \
  | python3 -c "import json,sys; data=json.load(sys.stdin); print(data[0]['sha'][:12])" 2>/dev/null \
  || echo "unknown")
echo "  SHA: ${COMMIT_SHA}"

# ---------- fetch SKILL.md ----------

echo "→ Fetching SKILL.md ..."
mkdir -p "${TARGET_DIR}"
fetch_raw "${RAW_BASE}/${UPSTREAM_SKILL_PATH}/SKILL.md" > "${TARGET_DIR}/SKILL.md"

# ---------- fetch references/ ----------

echo "→ Fetching references/ ..."
REF_LIST=$(fetch_json "${API_BASE}/contents/${UPSTREAM_SKILL_PATH}/references?ref=${BRANCH}" \
  | python3 -c "
import json, sys
data = json.load(sys.stdin)
if isinstance(data, list):
    for f in data:
        if f['type'] == 'file':
            print(f['name'])
")

mkdir -p "${TARGET_DIR}/references"

for fname in ${REF_LIST}; do
  echo "  ↓ references/${fname}"
  fetch_raw "${RAW_BASE}/${UPSTREAM_SKILL_PATH}/references/${fname}" > "${TARGET_DIR}/references/${fname}"
done

# ---------- write provenance ----------

SYNC_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "${TARGET_DIR}/SKILL_SOURCE.md" <<EOF
<!-- Auto-generated by scripts/sync-skill.sh — do not edit manually -->
- Upstream repo: https://github.com/${OWNER}/${REPO}
- Upstream path: ${UPSTREAM_SKILL_PATH}
- Upstream commit: ${COMMIT_SHA}
- Synced at: ${SYNC_DATE}
EOF

echo "→ Wrote provenance to ${TARGET_DIR}/SKILL_SOURCE.md"
echo "  Upstream commit: ${COMMIT_SHA}"
echo "  Synced at:       ${SYNC_DATE}"

# ---------- exit non-zero if git sees changes (CI drift check) ----------

if git -C "${SCRIPT_DIR}/.." rev-parse --is-inside-work-tree &>/dev/null; then
  CHANGED=$(git -C "${SCRIPT_DIR}/.." diff --name-only -- "${SKILL_PATH}" 2>/dev/null \
    ; git -C "${SCRIPT_DIR}/.." ls-files --others --exclude-standard -- "${SKILL_PATH}" 2>/dev/null)
  if [ -n "${CHANGED}" ]; then
    echo ""
    echo "DRIFT DETECTED — the following files differ from HEAD:"
    echo "${CHANGED}" | sed 's/^/  /'
    echo ""
    echo "Commit or PR these changes to resolve drift."
    exit 1
  fi
fi

echo "✓ Skill sync complete — no drift detected."
